### ISSUE TITLE
db_structure.sql data inconsistency

### ISSUE THREAD

**Issue by dawnstrider** [Sarjuuk/aowow#58]
In the current commit c75777e5c3270f0f621909c8c323193a91cc253e there is an syntax error in setup/structure.sql:

Line 2451: 
`INSERT INTO 'aowow_account' VALUES (0,0,'<system>','','AoWoW','',0,0,0,0,'','',0,0,0,0,'','','',0,0,0,0,0,'','');`

The values structure does not match the table structure. The correct values would be something like this:

`INSERT INTO 'aowow_account' VALUES (0,0,'<system>','','AoWoW','',0,0,0,0,'','',0,0,0,0,'','','',0,0,0,'');`

**Comment by Sarjuuk** [comment]
aw crap, some edits to the account-site have snuck in.

ty

**Comment by Sarjuuk** [comment]
fixed id b84854d4bab5c764e268e2653f52c9a1c29b7f83

**Comment by dawnstrider** [comment]
Sorry but still not fixed correctly in latest path.

The last 5 digit values are actually only 3.

**Comment by Sarjuuk** [comment]
oh for f sake.. >.<

fixed in c75777e5c3270f0f621909c8c323193a91cc253e (i hope)
